/**
 * RFC 7807 Problem Details for HTTP APIs
 * Standardized error response format.
 */
export interface ProblemDetails {
  /** A URI reference that identifies the problem type. */
  type: string;
  /** A short, human-readable summary of the problem type. */
  title: string;
  /** The HTTP status code generated by the origin server for this occurrence of the problem. */
  status: number;
  /** A human-readable explanation specific to this occurrence of the problem. */
  detail?: string;
  /** A URI reference that identifies the specific occurrence of the problem. */
  instance?: string;
  /** Optional validation errors mapping fields to error messages. */
  errors?: Record<string, string[]>;
}
