/**
 * Unit tests: GeneratedHeaderRule
 */

import { describe, it, expect } from "vitest";
import { GeneratedHeaderRule } from "../rules/generated-header.rule.js";
import { makeFile, makeContext } from "./helpers.js";

describe("GeneratedHeaderRule", () => {
  const rule = new GeneratedHeaderRule();
  const ctx = makeContext();

  it("has the correct rule ID", () => {
    expect(rule.id).toBe("GENERATED_HEADER");
  });

  describe("pass-through: no patch", () => {
    it("returns null when patch is null", () => {
      expect(rule.evaluate(makeFile({ path: "src/generated.ts", patch: null }), ctx)).toBeNull();
    });
  });

  describe("generated header patterns", () => {
    const generatedHeaders = [
      // Go/protobuf
      { description: "// Code generated", patch: "// Code generated by protoc-gen-go\n+type Foo struct{}" },
      { description: "// DO NOT EDIT", patch: "// DO NOT EDIT\n+package foo" },
      // TypeScript/JS codegen
      { description: "// This file is auto-generated", patch: "// This file is auto-generated by graphql-codegen\n+export type Query = {" },
      { description: "// Auto-generated by", patch: "// Auto-generated by openapi-generator\n+export interface Foo {" },
      { description: "// @generated", patch: "// @generated\n+const schema = gql`" },
      // Hash-style comments
      { description: "# auto-generated", patch: "# auto-generated by rails\n+# frozen_string_literal: true" },
      { description: "# This file is auto-generated", patch: "# This file is auto-generated by bundler\n+GEM" },
      // HTML comments
      { description: "<!-- auto-generated -->", patch: "<!-- auto-generated by template engine -->\n+<html>" },
      { description: "<!-- Do not edit -->", patch: "<!-- Do not edit this file directly -->\n+<html>" },
      // With diff markers
      { description: "+// Code generated (with + marker)", patch: "+// Code generated by protoc-gen-go\n+type Foo struct{}" },
    ];

    for (const { description, patch } of generatedHeaders) {
      it(`excludes file with header: "${description}"`, () => {
        const file = makeFile({ path: "src/auto.ts", patch });
        const result = rule.evaluate(file, ctx);

        expect(result).not.toBeNull();
        expect(result!.decision).toBe("excluded");
        expect(result!.matched).toBe(true);
        expect(result!.ruleId).toBe("GENERATED_HEADER");
      });
    }

    it("is case-insensitive", () => {
      const patch = "// CODE GENERATED\n+type Foo struct {}";
      expect(rule.evaluate(makeFile({ path: "src/auto.go", patch }), ctx)?.decision).toBe("excluded");
    });

    it("only scans the first 10 lines of the patch", () => {
      const prefix = Array(10).fill("context line").join("\n") + "\n";
      const patch = prefix + "// Code generated\n+type Foo struct {}";
      // The generated header appears AFTER the first 10 lines — should NOT be caught
      expect(rule.evaluate(makeFile({ path: "src/auto.go", patch }), ctx)).toBeNull();
    });

    it("catches header within the first 10 lines", () => {
      const prefix = Array(5).fill("context line").join("\n") + "\n";
      const patch = prefix + "// Code generated\n+type Foo struct {}";
      expect(rule.evaluate(makeFile({ path: "src/auto.go", patch }), ctx)?.decision).toBe("excluded");
    });
  });

  describe("normal source files pass through", () => {
    it("does not exclude a normal TypeScript file", () => {
      const patch = "@@ -1,3 +1,3 @@\n-const x = 1;\n+const x = 2;";
      expect(rule.evaluate(makeFile({ path: "src/index.ts", patch }), ctx)).toBeNull();
    });

    it("does not exclude a file with a comment that is not a generation marker", () => {
      const patch = "// This is a manually written file\n+export const x = 1;";
      expect(rule.evaluate(makeFile({ path: "src/config.ts", patch }), ctx)).toBeNull();
    });
  });
});
